<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>G.I.T Software Downloads · Avesta Enterprises</title><meta name="description" content="Download the G.I.T Windows device health reporting test build and request setup support from Avesta."><link rel="stylesheet" href="/assets/avesta/styles.css?v=20261002-guided"><link rel="icon" href="/icons/icon-192.png"></head>
<body><header class="wrap" style="padding:24px"><a class="link" href="/">Avesta Enterprises</a> · <a class="link" href="/index.php?page=it">IT services</a></header>
<main><section class="section"><div class="wrap narrow"><div class="eyebrow">Avesta Consulting · Software & support</div><h1>G.I.T device health reporting</h1><p style="margin-top:24px">Help your IT team see device health, disk space, CPU and memory usage, network status and Microsoft Defender status. Avesta offers setup and support for authorized device monitoring.</p>
<div class="notice">Unsigned test build · Windows validation pending. Designed for Windows 10/11 on Intel/AMD x64 PCs; 32-bit Windows and ARM are not supported. Requires Windows PowerShell 5.1 and administrator permission.</div>
<h2>Download for Windows</h2><div class="actions"><a class="button blue" href="/downloads/g-it/G-IT-Setup-x64.exe" download>Download Windows installer</a><a class="button secondary" href="/downloads/g-it/g-it-windows.zip" download>Download ZIP package</a></div><p style="margin-top:16px">The ZIP includes the installer, instructions, source and Windows validation checklist. This build has not been executed on Windows here and is not approved for wider deployment yet.</p>
<p style="margin-top:16px"><a class="link" href="/downloads/g-it/README.txt">Read installation instructions</a> · <a class="link" href="/downloads/g-it/SHA256SUMS.txt">Download checksums</a></p>
<h2 style="margin-top:40px">Before you install</h2><ol style="padding-left:24px;line-height:1.8"><li>Contact Avesta to arrange a compatible HTTPS G.I.T server and a one-time enrollment code. Downloading alone does not connect your PC.</li><li>Use an authorized test PC and review the included collection notice and validation checklist.</li><li>Open the installer, approve the disclosed installation and enter your server URL and enrollment code.</li><li>Complete the Windows checks before deploying to other PCs. If security software blocks this unsigned build, contact IT; do not bypass security controls.</li></ol>
<h2 style="margin-top:40px">What it reports</h2><p>Device identifiers (including hostname and serial number), operating system and hardware details, aggregate performance, disk health, network route presence and Defender status, including active threat names. A visible scheduled task reports at startup and every five minutes to your configured server.</p><p style="margin-top:16px">It does not collect keystrokes, passwords, browsing history, screenshots or file contents. This package reports health; it does not perform remote repairs, backup or recovery. Remove it through Windows Installed apps when no longer needed.</p>
<div class="actions"><a class="button blue" href="mailto:info@avesta.solutions?subject=G.I.T%20setup%20and%20support">Request G.I.T setup support</a><a class="link" href="tel:+260769974200">Call 0769 974 200</a></div></div></section></main><footer class="wrap" style="padding:24px">Avesta Enterprises · <a href="mailto:info@avesta.solutions">info@avesta.solutions</a></footer></body></html>
