import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {readFileSync} from 'node:fs';
import {createGuidedHelp} from '../assets/avesta/guided.js';
const guides=JSON.parse(readFileSync('assets/avesta/help.json','utf8'));
function setup(){const w=new Window();w.document.body.innerHTML='<section><form id="chat-form"></form></section>';const log=[];const panel=w.document.querySelector('section');const g=createGuidedHelp(panel,(_,x)=>log.push(x));const click=text=>{const b=[...panel.querySelectorAll('button')].find(b=>b.textContent===text);assert.ok(b,text);b.click();};return {w,panel,log,g,click};}
test('Collect details, advance checks and verify resolution explicitly',async()=>{const {w,panel,log,g,click}=setup();g.start('printer offline',guides);for(const a of ['HP printer','Windows 11','Offline','Checked cable'])g.start(a,guides);assert.match(log.at(-1).answer,/Check 1 of/);click('Still failing');assert.match(log.at(-1).answer,/Check 2 of/);click('Fixed');assert.match(log.at(-1).answer,/repeat the task/);assert.ok(!log.some(x=>x.answer.startsWith('Marked resolved')));click('Yes, verified');assert.match(log.at(-1).answer,/Marked resolved/);g.clear();assert.equal(panel.querySelector('.guided-help').textContent,'');await w.happyDOM.close();});
test('Escalation includes attempts and editable, user-sent summary',async()=>{const {w,panel,g,click}=setup();g.start('wifi keeps dropping',guides);for(const a of ['Laptop','macOS','Disconnects','Moved closer'])g.start(a,guides);click('Still failing');click('Contact IT');const area=panel.querySelector('textarea');assert.match(area.value,/Laptop/);assert.match(area.value,/Tried; still failing/);area.value='Reviewed summary';area.dispatchEvent(new w.Event('input'));assert.ok(panel.querySelector('a').href.includes('Reviewed%20summary'));assert.equal(panel.querySelector('a[target="_blank"]').rel,'noopener noreferrer');await w.happyDOM.close();});
test('Risk signals escalate immediately without ordinary repair checks',async()=>{const {w,panel,log,g}=setup();g.start('computer has a burning smell',guides);assert.ok(panel.querySelector('#git-summary'));assert.ok(log.some(x=>x.answer.includes('Stop troubleshooting')));assert.ok(!log.some(x=>/^Check \d/.test(x.answer)));await w.happyDOM.close();});
test('Unknown issues collect context then hand off without inventing fixes',async()=>{const {w,panel,log,g}=setup();g.start('Belina unexpected application error',guides);for(const a of ['Dell laptop','Windows 11','Error 99','Restarted app'])g.start(a,guides);assert.ok(panel.querySelector('#git-summary'));assert.ok(log.some(x=>x.answer.includes('do not have a verified saved guide')));await w.happyDOM.close();});
test('Non-Windows users do not receive Windows-only steps',async()=>{const {w,log,g,click,panel}=setup();g.start('printer offline',guides);for(const a of ['Canon','macOS','Offline','None'])g.start(a,guides);while([...panel.querySelectorAll('button')].some(b=>b.textContent==='Already tried / skip'))click('Already tried / skip');assert.ok(!log.filter(x=>/^Check \d/.test(x.answer)).some(x=>x.answer.includes('Windows')));await w.happyDOM.close();});
